/**
 * TMQL4J Plugin for Ontopia
 * 
 * Copyright: Copyright 2009 Topic Maps Lab, University of Leipzig. http://www.topicmapslab.de/    
 * License:   Apache License, Version 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
 * 
 * Author: Sven Krosse
 * 
 */
package net.ontopia.topicmaps.query.tmql.impl.tmql4jextension;

import de.topicmapslab.tmql4j.common.core.exception.TMQLRuntimeException;
import de.topicmapslab.tmql4j.common.core.process.ProcessingTaskChainImpl;
import de.topicmapslab.tmql4j.common.core.runtime.TMQLRuntime;
import de.topicmapslab.tmql4j.common.model.query.IQuery;
import de.topicmapslab.tmql4j.common.model.runtime.ITMQLRuntime;
import de.topicmapslab.tmql4j.interpreter.core.base.QueryMatches;
import de.topicmapslab.tmql4j.parser.model.IParser;
import de.topicmapslab.tmql4j.parser.model.IParserTree;

public class OntopiaParserProcessingTaskChain extends ProcessingTaskChainImpl {

	public OntopiaParserProcessingTaskChain(final ITMQLRuntime runtime,
			final IQuery query) {
		super((TMQLRuntime) runtime, query);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected QueryMatches doInterpretationTask(TMQLRuntime runtime,
			IParser parser) throws TMQLRuntimeException {
		return new QueryMatches(runtime);
	}

	/**
	 * Return the parsing tree generated by the processing chain
	 * 
	 * @return
	 */
	public IParserTree getParserTree() {
		return getRuntime().getValueStore().getParserTree();
	}

}
